general:
  enable_incomplete_verification: False
  conv_mode: matrix
model:
  onnx_path: ../Benchmarks/onnx/bloom_filter.onnx
specification:
  vnnlib_path: ../Benchmarks/vnnlib/bloom_filter_6.vnnlib
solver:
  batch_size: 2048
bab:
  branching:
    method: sb
    sb_coeff_thresh: 0.1
    input_split:
      enable: True