general:
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: matrix
model:
  onnx_path: ../Benchmarks/onnx/mscn_128d.onnx
specification:
  vnnlib_path: ../Benchmarks/vnnlib/mscn_128d_7.vnnlib
solver:
  batch_size: 50  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  initial_max_domains: 100000
  branching:
    method: naive  # Split on input space.
    input_split:
      enable: True
      adv_check: .inf
