general:
  enable_incomplete_verification: False
  loss_reduction_func: max
  conv_mode: matrix
model:
  onnx_path: ../Benchmarks/onnx/lindex.onnx
specification:
  vnnlib_path: ../Benchmarks/vnnlib/lindex_2_3.vnnlib
solver:
  batch_size: 128  # Number of parallel domains to compute on GPU.
  bound_prop_method: forward+backward
  beta-crown:
    iteration: 10  # Iterations for computing intermediate layer bounds.
bab:
  initial_max_domains: 1000
  branching:
    method: naive  # Split on input space.
    input_split:
      enable: True
      adv_check: .inf
